### ISSUE TITLE
FF32 as f32

### ISSUE THREAD

**Issue by Bkeinn** [bend-n/umath#1]
Is there a way to convert an FF32 back to an f32?

**Comment by bend-n** [comment]
multiple, actually.
```rs
let f = unsafe { FF32::new(0) };
let x: f32 = *f;
let y: f32 = f.get()
```

**Comment by bend-n** [comment]
Note that `as` conversions are language defined, which makes things such as `f as f32` impossible.

**Comment by bend-n** [comment]
Also, I *could* make a "unsafe feature flag" that adds a `Default` and `From` impl

**Comment by Bkeinn** [comment]
get is enough thank you for the crate and the fast response.
